// Code generated by gomarvin, v0.10.x. DO NOT EDIT.
// Rename the current file and remove upper comment to save changes!

package cron_module

type CreateCronBody struct {
	Taskname string `json:"taskname" validate:"required"`
	At       string `json:"at" validate:"required"`
}

type UpdateCronBody struct {
	Taskname string `json:"taskname" validate:"required"`
	At       string `json:"at" validate:"required"`
}
