// Code generated by gomarvin, v0.10.x. DO NOT EDIT.
// Rename the current file, remove upper comment
// and replace __ to save changes!

package cron_module

import (
	"fmt"
	res "go-http/internal/api/response"

	"github.com/go-chi/chi/v5"
	"net/http"

	"strconv"

	"strconv"

	"go-http/pkg/validate"
)

const (
	__GetCronsUrl   = "/cron"
	__GetCronUrl    = "/cron/{id}"
	__CreateCronUrl = "/cron"
	__DeleteCronUrl = "/cron/{id}"
	__UpdateCronUrl = "/cron/{id}"
)

func Router__(api *chi.Mux) {
	api.Get(__GetCronsUrl, __GetCrons)
	api.Get(__GetCronUrl, __GetCron)
	api.Post(__CreateCronUrl, __CreateCron)
	api.Delete(__DeleteCronUrl, __DeleteCron)
	api.Put(__UpdateCronUrl, __UpdateCron)
}

// GET URL/cron
func __GetCrons(w http.ResponseWriter, r *http.Request) {

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(w, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(w, 200, data, "", res.PaginationLinks{})
}

// GET URL/cron/[id:int]
func __GetCron(w http.ResponseWriter, r *http.Request) {

	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		res.Response(w, 400, nil, res.ParamIsNotIntMessage)
		return
	}
	_ = id

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(w, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(w, 200, data, "")
}

// POST URL/cron
func __CreateCron(w http.ResponseWriter, r *http.Request) {

	// validate the sent body
	payload := new(CreateCronBody)
	if err := validate.RequestBody(r, payload); err != nil {
		res.Response(w, 400, err, res.FailedPayloadValidationMessage)
		return
	}

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(w, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(w, 200, data, "")
}

// DELETE URL/cron/[id:string]
func __DeleteCron(w http.ResponseWriter, r *http.Request) {

	id := chi.URLParam(r, "id")
	_ = id

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(w, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(w, 200, data, "")
}

// PUT URL/cron/[id:int]
func __UpdateCron(w http.ResponseWriter, r *http.Request) {

	// validate the sent body
	payload := new(UpdateCronBody)
	if err := validate.RequestBody(r, payload); err != nil {
		res.Response(w, 400, err, res.FailedPayloadValidationMessage)
		return
	}

	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		res.Response(w, 400, nil, res.ParamIsNotIntMessage)
		return
	}
	_ = id

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(w, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(w, 200, data, "")
}

// Placeholder function to be replaced in the controllers after codegen.
// Usually replaced with the function which returns the data from the db.
func placeholderFunc() (struct{}, error) {
	var placeholder struct{}
	return placeholder, nil
}
