// Code generated by gomarvin, v0.10.x. DO NOT EDIT.
// Rename the current file and remove upper comment to save changes!

package exec_module

type ExecBody struct {
	Taskname string `json:"taskname" validate:"required"`
}
